### ISSUE TITLE
A solution for workspaces

### ISSUE THREAD

**Issue by SimonBiggs** [deathbeds/jyve#38]
Hi @bollwyvl,

I had an idea for a solution to workspaces. If hosting was done with firebase then rewrites from /lab/workspaces/* could be pointed to the base html file:

https://firebase.google.com/docs/hosting/url-redirects-rewrites#section-rewrites

This solution would only work with firebase though. Can you think of another method?

**Comment by bollwyvl** [comment]
I haven't played with the workspace API properly, what is the use case you
expect?

At present, the only redirect is for / to /lab/. Instead of redirects, the
pages could be real copies of the base page, now that the baseurl is
dynamic... But you never know what evil things people will have to do with
window.location. better might be to adopt a #fragment-based url convention.

I'd like /lab/tree/Foo.ipynb to work, and that would be feasible if the
things wanted to hook were known in advance, but dumb static host can't
list contents, alas, webdav.

Another thing instead of a custom contents manager would be a whole client
side API mock: we've already mocked/patched the hardest part (kernel
websockets), so this would probably be reasonable.

Anyhow, all the fake page/api generation is pluggable (or at least
subclass-able), but it's doesn't seem like putting anything firebase (or
any other proprietary thing) -specific into Jyve core would be reasonable.
Gh pages is great, though it does have its quirks, it mostly works like any
other static host other than file://

**Comment by SimonBiggs** [comment]
Yup cheers, that makes sense.

**Comment by SimonBiggs** [comment]
Can the fragment based url convention work for the API as well? As in, could it be possible to reduce all the code down into a single hostable/sharable html file that calls a single cdn JavaScript file and a single cdn style file (ala the iodide notebook format, view source of https://iodide.io)?

Because if that was possible there might be able to end up being quite a bit of overlap between JupyterLab Jyve and Iodide. Might be able to leverage some common goals...

**Comment by SimonBiggs** [comment]
And holy moly it would be awesome to be able to take a notebook json file, wrap it a script and a html tag, and then slap on a jyve cdn script and style tag. Throw it on an email attachment and send it off to a friend who doesn't have any rights on their work machine. Open it up, and Bob's their uncle, they have a working instance of JupyterLab with my notebook opening first in a single document mode, file browser closed, set to the pyodide jyve kernel. ... Wow... That would be awesome. ...

**Comment by SimonBiggs** [comment]
And then being able to have "export notebook to Jyve" within JupyterLab proper. Which would just wack those tags on for you... ...
